### ISSUE TITLE
The encode option of VP9 and VP8 is missing

### ISSUE THREAD

**Issue by EasyVR** [75lb/handbrake-js#31] opened 2018-09-09 07:02 UTC

**Comment by 75lb** [comment] 2018-09-24 17:53
could you give me an example of a command which works with the official Handbrake CLI but not handbrake-js please? When you post an issue it helps to include some information so I can reproduce the issue.

**Comment by 75lb** [comment] 2018-10-01 09:38
Closing due to lack of information.

**Closed by 75lb** 2018-10-01 09:38 UTC
