### ISSUE TITLE
Invalid input error on Windows 10

### ISSUE THREAD

**Issue by marinsokol** [75lb/handbrake-js#52] opened 2020-02-10 11:09 UTC
I am getting error `Invalid input, not a video file [error code: 2]` on Windows 10 in Electron app. I am trying to convert webm file into mp4 like this:

```js
  hbjs 
    .spawn({
        input: "../../../Desktop/temp-output-screen-1581332234197.webm", 
         output: "../../../Desktop/output-screen-1581332234197.mp4"
     })
    .on('error', err => {
      console.log('err -> ', err)
    })
    .on('end', () => {
     console.log('end')
    })
```

This code works on Mac without any issues.

Thanks

**Comment by 75lb** [comment] 2020-03-19 18:17
so your Electron app works ok on Mac but not Windows? Did you find out what's going on?

**Comment by 75lb** [comment] 2020-04-23 10:09
closing as a duplicate of #54

**Closed by 75lb** 2020-04-23 10:09 UTC
